#ifndef TECHCOIN_CHAINPARAMSSEEDS_H
#define TECHCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the techcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
sstatic const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xa4,0x5a,0x8e,0x66,0x22,0x9f,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xa4,0x5a,0x8e,0x66,0x49,0xaf,
};

#endif // TECHCOIN_CHAINPARAMSSEEDS_H
